    columns:
      - name: country,
        description: Customer country

      - name: "customer id"
        description: Customer Identifier

      - name: "subscription date"
        description: subscription date