models:
  - name: dim_company
    description: "company data"
    columns:
      - name: company
        description: "compnay name"

  - name: dim_county
    description: "country data"
    columns:
      - name: city
        description: "city name"

      - name: country
        description: "country name"